'use client'
import { AlertGlobalContextProvider } from './ContextApi/AlertContextProvider';
import { GlobalContextProvider } from './ContextApi/AppContextProvider';
import NavBar from './components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import { useRouter, usePathname, useSearchParams } from 'next/navigation';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={"max-w-full w-screen relative overflow-y-auto scrollbar-stable" + (inter.className)}>
          
        <GlobalContextProvider>
          <AlertGlobalContextProvider>
            {pathname != '/signup' && (<NavBar />)}
            {/* <NavBar /> */}
            {children}
          </AlertGlobalContextProvider>
        </GlobalContextProvider>
          
      </body>
    </html>
  )
}
